def on_forever():
    basic.show_icon(IconNames.NO)
    pins.digital_write_pin(DigitalPin.P0, 1)
    basic.pause(5000)
    pins.digital_write_pin(DigitalPin.P0, 0)
    basic.pause(300)
    pins.digital_write_pin(DigitalPin.P0, 1)
    basic.pause(300)
    pins.digital_write_pin(DigitalPin.P0, 0)
    basic.pause(300)
    pins.digital_write_pin(DigitalPin.P0, 1)
    basic.pause(300)
    pins.digital_write_pin(DigitalPin.P0, 0)
    pins.digital_write_pin(DigitalPin.P1, 1)
    basic.pause(5000)
    pins.digital_write_pin(DigitalPin.P1, 0)
    basic.clear_screen()
    pins.digital_write_pin(DigitalPin.P2, 1)
    basic.show_number(5)
    basic.pause(300)
    basic.show_number(4)
    basic.pause(300)
    basic.show_number(3)
    basic.pause(300)
    basic.show_number(2)
    basic.pause(300)
    basic.show_number(1)
    pins.digital_write_pin(DigitalPin.P2, 0)
basic.forever(on_forever)
